if(UnityEditor.EditorApplication.isPlaying)throw new System.Exception("Stop Play mode before applying");
const string root="Assets/ChibiSurvivor/Player/SimpleHeroStudy", game=root+"/Game";
const string temporary=game+"/BatMotionImport.fbx";
var originalWalk=System.IO.File.ReadAllBytes(game+"/Walk.anim");var originalRun=System.IO.File.ReadAllBytes(game+"/Run.anim");
System.IO.File.Copy("D:/Demo/ArtWork/SimpleHeroMelee/Player_BatMotion.fbx",temporary,true);UnityEditor.AssetDatabase.ImportAsset(temporary,UnityEditor.ImportAssetOptions.ForceSynchronousImport);
var importer=(UnityEditor.ModelImporter)UnityEditor.AssetImporter.GetAtPath(temporary);importer.animationType=UnityEditor.ModelImporterAnimationType.Generic;importer.importAnimation=true;importer.resampleCurves=true;importer.animationCompression=UnityEditor.ModelImporterAnimationCompression.Off;importer.importCameras=false;importer.importLights=false;importer.avatarSetup=UnityEditor.ModelImporterAvatarSetup.CreateFromThisModel;importer.SaveAndReimport();
var clipSettings=importer.defaultClipAnimations;foreach(var clip in clipSettings){clip.loopTime=false;clip.loopPose=false;clip.keepOriginalPositionY=true;clip.keepOriginalPositionXZ=true;clip.keepOriginalOrientation=true;clip.lockRootRotation=true;clip.lockRootPositionXZ=true;clip.lockRootHeightY=true;}importer.clipAnimations=clipSettings;importer.SaveAndReimport();
AnimationClip SaveClip(AnimationClip clip,string name){clip.name=name;var path=game+"/"+name+".anim";var saved=UnityEditor.AssetDatabase.LoadAssetAtPath<AnimationClip>(path);if(saved==null){UnityEditor.AssetDatabase.CreateAsset(clip,path);return clip;}UnityEditor.EditorUtility.CopySerialized(clip,saved);UnityEngine.Object.DestroyImmediate(clip);return saved;}
var imported=UnityEditor.AssetDatabase.LoadAllAssetsAtPath(temporary).OfType<AnimationClip>().Single(c=>!c.name.StartsWith("__preview__"));
var copy=UnityEngine.Object.Instantiate(imported);var settings=UnityEditor.AnimationUtility.GetAnimationClipSettings(copy);settings.loopTime=false;UnityEditor.AnimationUtility.SetAnimationClipSettings(copy,settings);var swing=SaveClip(copy,"BatSwing");
var prefab=UnityEditor.AssetDatabase.LoadAssetAtPath<GameObject>(game+"/SimpleHero.prefab");var chest=prefab.GetComponentsInChildren<Transform>(true).Single(t=>t.name=="Chest");var chestPath=UnityEditor.AnimationUtility.CalculateTransformPath(chest,prefab.transform);
var walk=UnityEngine.Object.Instantiate(UnityEditor.AssetDatabase.LoadAssetAtPath<AnimationClip>(game+"/Walk.anim"));
foreach(var binding in UnityEditor.AnimationUtility.GetCurveBindings(swing))if(binding.path==chestPath||binding.path.StartsWith(chestPath+"/")){float value=UnityEditor.AnimationUtility.GetEditorCurve(swing,binding).Evaluate(0);UnityEditor.AnimationUtility.SetEditorCurve(walk,binding,AnimationCurve.Constant(0,walk.length,value));}
settings=UnityEditor.AnimationUtility.GetAnimationClipSettings(walk);settings.loopTime=true;UnityEditor.AnimationUtility.SetAnimationClipSettings(walk,settings);walk=SaveClip(walk,"BatWalk");
var controller=UnityEditor.AssetDatabase.LoadAssetAtPath<UnityEditor.Animations.AnimatorController>(game+"/SimpleHero.controller");var sm=controller.layers[0].stateMachine;
foreach(var clip in new[]{swing,walk}){var state=sm.states.Select(s=>s.state).FirstOrDefault(s=>s.name==clip.name)??sm.AddState(clip.name);state.motion=clip;if(clip==swing){state.speedParameter="SlashSpeed";state.speedParameterActive=true;}}
if(!controller.layers.Any(l=>l.name=="BatHold"))controller.AddLayer("BatHold");var layers=controller.layers;var layer=layers.Single(l=>l.name=="BatHold");layer.avatarMask=UnityEditor.AssetDatabase.LoadAssetAtPath<AvatarMask>(game+"/SwordUpperBody.mask");layer.defaultWeight=0;layer.blendingMode=UnityEditor.Animations.AnimatorLayerBlendingMode.Override;var hold=layer.stateMachine.states.Select(s=>s.state).FirstOrDefault(s=>s.name=="Hold")??layer.stateMachine.AddState("Hold");hold.motion=walk;hold.speed=0;layer.stateMachine.defaultState=hold;controller.layers=layers;UnityEditor.EditorUtility.SetDirty(controller);
var meshData=Newtonsoft.Json.Linq.JObject.Parse(System.IO.File.ReadAllText("Library/player-bat-mesh.json"));
var importedModel=UnityEditor.AssetDatabase.LoadAssetAtPath<GameObject>(temporary);
var importedBat=importedModel.GetComponentsInChildren<SkinnedMeshRenderer>(true).Single(x=>x.name=="Hero_Bat");
var boneIndex=System.Array.FindIndex(importedBat.bones,t=>t.name=="HandSocket.R");
var mesh=UnityEngine.Object.Instantiate(importedBat.sharedMesh);mesh.name="Player_Bat";
var bind=mesh.bindposes[boneIndex];var boneScale=importedBat.bones[boneIndex].lossyScale;
mesh.vertices=mesh.vertices.Select(v=>Vector3.Scale(bind.MultiplyPoint3x4(v),boneScale)).ToArray();
// The original bat authoring mesh has inward face winding; correct the rigid copy.
for(int sub=0;sub<mesh.subMeshCount;sub++){var tri=mesh.GetTriangles(sub);for(int i=0;i<tri.Length;i+=3){int n=tri[i+1];tri[i+1]=tri[i+2];tri[i+2]=n;}mesh.SetTriangles(tri,sub);}
mesh.boneWeights=new BoneWeight[0];mesh.bindposes=new Matrix4x4[0];mesh.RecalculateNormals();mesh.RecalculateBounds();var meshPath=game+"/BatMesh.asset";var savedMesh=UnityEditor.AssetDatabase.LoadAssetAtPath<Mesh>(meshPath);if(savedMesh==null){UnityEditor.AssetDatabase.CreateAsset(mesh,meshPath);savedMesh=mesh;}else{UnityEditor.EditorUtility.CopySerialized(mesh,savedMesh);UnityEngine.Object.DestroyImmediate(mesh);}
var materials=new System.Collections.Generic.List<Material>();foreach(var info in meshData["materials"]){var path=root+"/Materials/Player_"+(string)info["name"]+".mat";var mat=UnityEditor.AssetDatabase.LoadAssetAtPath<Material>(path);if(mat==null){mat=new Material(Shader.Find("Universal Render Pipeline/Lit"));var c=info["color"];mat.SetColor("_BaseColor",new Color((float)c[0],(float)c[1],(float)c[2]).gamma);mat.SetFloat("_Smoothness",1-(float)info["roughness"]);UnityEditor.AssetDatabase.CreateAsset(mat,path);}materials.Add(mat);}
var instance=UnityEditor.PrefabUtility.LoadPrefabContents(game+"/SimpleHero.prefab");try{var socket=instance.GetComponentsInChildren<Transform>(true).Single(t=>t.name=="HandSocket.R");var bat=instance.GetComponentsInChildren<Transform>(true).FirstOrDefault(t=>t.name=="Hero_Bat")?.gameObject??new GameObject("Hero_Bat");bat.transform.SetParent(socket,false);bat.transform.localPosition=Vector3.zero;bat.transform.localRotation=Quaternion.identity;var scale=socket.lossyScale;bat.transform.localScale=new Vector3(1/scale.x,1/scale.y,1/scale.z);var filter=bat.GetComponent<MeshFilter>();if(filter==null)filter=bat.AddComponent<MeshFilter>();filter.sharedMesh=savedMesh;var renderer=bat.GetComponent<MeshRenderer>();if(renderer==null)renderer=bat.AddComponent<MeshRenderer>();renderer.sharedMaterials=materials.ToArray();renderer.enabled=false;UnityEditor.PrefabUtility.SaveAsPrefabAsset(instance,game+"/SimpleHero.prefab");}finally{UnityEditor.PrefabUtility.UnloadPrefabContents(instance);}
var item=UnityEditor.AssetDatabase.LoadAssetAtPath<ItemData>("Assets/Resources/Items/Weapon/Bat.asset");const string weaponPath="Assets/Resources/WeaponData/Weapon_Bat.asset";var weapon=UnityEditor.AssetDatabase.LoadAssetAtPath<WeaponData>(weaponPath);if(weapon==null){weapon=ScriptableObject.CreateInstance<WeaponData>();weapon.weaponId="bat";UnityEditor.AssetDatabase.CreateAsset(weapon,weaponPath);}weapon.useTwoHandBatAnimations=true;weapon.useTwoHandSwordAnimations=false;
var player=UnityEditor.AssetDatabase.LoadAssetAtPath<GameObject>("Assets/Resources/PlayerRig.prefab").GetComponentInChildren<TopDownPlayer>(true);var so=new UnityEditor.SerializedObject(player);var stat=StatDB.Instance.playerStat;var make=typeof(TopDownPlayer).GetMethod("MakeAttack",System.Reflection.BindingFlags.NonPublic|System.Reflection.BindingFlags.Static);
var defaultCombo=so.FindProperty("lightCombo").objectReferenceValue as AttackComboData;
AttackData Attack(string name,AttackData template,float damage,float groggy,float range,float hitstop){var a=template!=null?UnityEngine.Object.Instantiate(template):(AttackData)make.Invoke(null,new object[]{name,6,damage,groggy,range,2,3,hitstop});a.attackId=name;a.name=name;a.fps=30;a.totalFrames=48;a.cancelFromFrame=-1;foreach(var window in a.windows){window.startFrame=17;window.endFrame=21;}var path="Assets/Resources/WeaponData/"+name+".asset";var saved=UnityEditor.AssetDatabase.LoadAssetAtPath<AttackData>(path);if(saved==null){UnityEditor.AssetDatabase.CreateAsset(a,path);return a;}UnityEditor.EditorUtility.CopySerialized(a,saved);UnityEngine.Object.DestroyImmediate(a);return saved;}
var light=Attack("Bat_Light",defaultCombo?.GetStep(0),stat.lightDamage,stat.lightGroggy,stat.lightRange,.03f);
weapon.heavyAttack=Attack("Bat_Heavy",so.FindProperty("heavyAttack").objectReferenceValue as AttackData,stat.heavyDamage,stat.heavyGroggy,stat.heavyRange,.05f);
weapon.heavyFullAttack=Attack("Bat_HeavyFull",so.FindProperty("heavyFullAttack").objectReferenceValue as AttackData,stat.heavyFullDamage,stat.heavyFullGroggy,stat.heavyRange*1.2f,.06f);
const string comboPath="Assets/Resources/WeaponData/Bat_SingleHit.asset";var combo=UnityEditor.AssetDatabase.LoadAssetAtPath<AttackComboData>(comboPath);if(combo==null){combo=ScriptableObject.CreateInstance<AttackComboData>();UnityEditor.AssetDatabase.CreateAsset(combo,comboPath);}combo.comboId="bat_single_hit";combo.steps=new System.Collections.Generic.List<AttackData>{light};weapon.lightCombo=combo;item.weaponData=weapon;foreach(var o in new UnityEngine.Object[]{combo,weapon,item})UnityEditor.EditorUtility.SetDirty(o);UnityEditor.AssetDatabase.SaveAssets();
// Import-only FBX is not a gameplay dependency; retain it outside the project.
var archived="D:/Demo/ArtWork/SimpleHeroMelee/ImportedForBat";System.IO.Directory.CreateDirectory(archived);foreach(var p in new[]{temporary,temporary+".meta"}){var target=System.IO.Path.GetFullPath(System.IO.Path.Combine(archived,System.IO.Path.GetFileName(p)));var source=System.IO.Path.GetFullPath(p);if(!source.StartsWith(System.IO.Path.GetFullPath(game)+System.IO.Path.DirectorySeparatorChar)||!target.StartsWith(archived.Replace('/',System.IO.Path.DirectorySeparatorChar)+System.IO.Path.DirectorySeparatorChar))throw new System.Exception("Invalid cleanup path");if(System.IO.File.Exists(target))target+="."+System.DateTime.Now.Ticks;System.IO.File.Move(source,target);}UnityEditor.AssetDatabase.Refresh();
if(!originalWalk.SequenceEqual(System.IO.File.ReadAllBytes(game+"/Walk.anim"))||!originalRun.SequenceEqual(System.IO.File.ReadAllBytes(game+"/Run.anim")))throw new System.Exception("Locomotion changed");
return new{applied=true,clip=swing.name,seconds=swing.length,weapon=item.itemId,singleHit=combo.StepCount==1,hitWindow=new[]{17,21},locomotionPreserved=true};
