// After rebuilding base clips, run refine_simple_bandit_motion.cs, then rebuild_bandit_grounded_walk.cs (replaces the superseded additive walk).
const string folder="Assets/ChibiSurvivor/Bandit/SimpleBandit", hero="Assets/ChibiSurvivor/Player/SimpleHeroStudy/Game";
UnityEditor.AssetDatabase.Refresh();
foreach(var name in new[]{"Animations","Weapons/Materials"}){var path=folder+"/"+name;if(!UnityEditor.AssetDatabase.IsValidFolder(path))UnityEditor.AssetDatabase.CreateFolder(System.IO.Path.GetDirectoryName(path).Replace('\\','/'),System.IO.Path.GetFileName(path));}
var protectedFiles=new[]{hero+"/Idle.anim",hero+"/Walk.anim",hero+"/Run.anim",hero+"/BatWalk.anim",hero+"/BatSwing.anim","Assets/Resources/Characters/Bandit01.prefab"};
var hashes=protectedFiles.ToDictionary(p=>p,p=>System.IO.File.ReadAllBytes(p));
AnimationClip Source(string name)=>UnityEditor.AssetDatabase.LoadAssetAtPath<AnimationClip>(hero+"/"+name+".anim")??throw new System.Exception("Missing source "+name);
var sourceAttack=Source("BatSwing");var heroPrefab=UnityEditor.AssetDatabase.LoadAssetAtPath<GameObject>(hero+"/SimpleHero.prefab");
string chestPath=UnityEditor.AnimationUtility.CalculateTransformPath(heroPrefab.GetComponentsInChildren<Transform>(true).Single(t=>t.name=="Chest"),heroPrefab.transform);
AnimationClip MakeClip(string source,string name,bool loop,bool holdUpper,float factor=1){
 var clip=UnityEngine.Object.Instantiate(Source(source));clip.name=name;
 if(holdUpper){float length=clip.length;foreach(var binding in UnityEditor.AnimationUtility.GetCurveBindings(sourceAttack))if(binding.path==chestPath||binding.path.StartsWith(chestPath+"/")){float value=UnityEditor.AnimationUtility.GetEditorCurve(sourceAttack,binding).Evaluate(0);UnityEditor.AnimationUtility.SetEditorCurve(clip,binding,AnimationCurve.Constant(0,length,value));}}
 if(factor!=1){foreach(var binding in UnityEditor.AnimationUtility.GetCurveBindings(clip)){var curve=UnityEditor.AnimationUtility.GetEditorCurve(clip,binding);var keys=curve.keys;for(int i=0;i<keys.Length;i++){keys[i].time*=factor;keys[i].inTangent/=factor;keys[i].outTangent/=factor;}curve.keys=keys;UnityEditor.AnimationUtility.SetEditorCurve(clip,binding,curve);}var events=UnityEditor.AnimationUtility.GetAnimationEvents(clip);foreach(var e in events)e.time*=factor;UnityEditor.AnimationUtility.SetAnimationEvents(clip,events);}
 var settings=UnityEditor.AnimationUtility.GetAnimationClipSettings(clip);settings.loopTime=loop;settings.loopBlend=false;settings.startTime=0;settings.stopTime=Source(source).length*factor;UnityEditor.AnimationUtility.SetAnimationClipSettings(clip,settings);
 var path=folder+"/Animations/"+name+".anim";var saved=UnityEditor.AssetDatabase.LoadAssetAtPath<AnimationClip>(path);if(saved==null){UnityEditor.AssetDatabase.CreateAsset(clip,path);return clip;}UnityEditor.EditorUtility.CopySerialized(clip,saved);UnityEngine.Object.DestroyImmediate(clip);return saved;
}
var idle=MakeClip("Idle","Bandit_BatIdle",true,true);var walk=MakeClip("BatWalk","Bandit_BatWalk",true,false);var run=MakeClip("Run","Bandit_BatRun",true,true);var attack=MakeClip("BatSwing","Bandit_BatAttack",false,false,.9f);
string modelPath=folder+"/Weapons/BanditClub.fbx";var importer=(UnityEditor.ModelImporter)UnityEditor.AssetImporter.GetAtPath(modelPath);importer.isReadable=true;importer.importAnimation=false;importer.importCameras=false;importer.importLights=false;importer.SaveAndReimport();
string texturePath=folder+"/Weapons/Textures/BanditClub_BaseColor.png";var ti=(UnityEditor.TextureImporter)UnityEditor.AssetImporter.GetAtPath(texturePath);ti.sRGBTexture=true;ti.textureCompression=UnityEditor.TextureImporterCompression.Uncompressed;ti.maxTextureSize=512;ti.wrapMode=TextureWrapMode.Clamp;ti.SaveAndReimport();
var imported=UnityEditor.AssetDatabase.LoadAssetAtPath<GameObject>(modelPath).GetComponentsInChildren<SkinnedMeshRenderer>(true).Single(r=>r.name=="Bandit_Club");
var mesh=UnityEngine.Object.Instantiate(imported.sharedMesh);mesh.name="BanditClub";int index=System.Array.FindIndex(imported.bones,b=>b.name=="HandSocket.R");if(index<0)throw new System.Exception("Weapon socket");
var bind=mesh.bindposes[index];var scale=imported.bones[index].lossyScale;mesh.vertices=mesh.vertices.Select(v=>Vector3.Scale(bind.MultiplyPoint3x4(v),scale)).ToArray();mesh.boneWeights=new BoneWeight[0];mesh.bindposes=new Matrix4x4[0];mesh.RecalculateNormals();mesh.RecalculateBounds();
string meshPath=folder+"/Weapons/BanditClubMesh.asset";var savedMesh=UnityEditor.AssetDatabase.LoadAssetAtPath<Mesh>(meshPath);if(savedMesh==null){UnityEditor.AssetDatabase.CreateAsset(mesh,meshPath);savedMesh=mesh;}else{UnityEditor.EditorUtility.CopySerialized(mesh,savedMesh);UnityEngine.Object.DestroyImmediate(mesh);}
var materialPath=folder+"/Weapons/Materials/BanditClub_Surface.mat";var material=UnityEditor.AssetDatabase.LoadAssetAtPath<Material>(materialPath);if(material==null){material=new Material(Shader.Find("Universal Render Pipeline/Lit"));UnityEditor.AssetDatabase.CreateAsset(material,materialPath);}material.SetTexture("_BaseMap",UnityEditor.AssetDatabase.LoadAssetAtPath<Texture2D>(texturePath));material.SetColor("_BaseColor",Color.white);material.SetFloat("_Smoothness",.12f);material.SetFloat("_Metallic",0);material.SetFloat("_SpecularHighlights",0);material.EnableKeyword("_SPECULARHIGHLIGHTS_OFF");UnityEditor.EditorUtility.SetDirty(material);
var weapon=new GameObject("Bandit_Club");try{weapon.AddComponent<MeshFilter>().sharedMesh=savedMesh;weapon.AddComponent<MeshRenderer>().sharedMaterial=material;UnityEditor.PrefabUtility.SaveAsPrefabAsset(weapon,folder+"/Weapons/BanditClub.prefab");}finally{UnityEngine.Object.DestroyImmediate(weapon);}
var controller=UnityEditor.AssetDatabase.LoadAssetAtPath<UnityEditor.Animations.AnimatorController>(folder+"/SimpleBandit.controller");controller.layers=new[]{controller.layers[0]};if(!controller.parameters.Any(p=>p.name=="Attack"))controller.AddParameter("Attack",AnimatorControllerParameterType.Trigger);
var sm=controller.layers[0].stateMachine;UnityEditor.Animations.AnimatorState State(string n)=>sm.states.Select(s=>s.state).FirstOrDefault(s=>s.name==n)??sm.AddState(n);
var locomotion=State("Locomotion");var tree=(UnityEditor.Animations.BlendTree)locomotion.motion;tree.children=new[]{new UnityEditor.Animations.ChildMotion{motion=idle,threshold=0,timeScale=1},new UnityEditor.Animations.ChildMotion{motion=walk,threshold=1,timeScale=1},new UnityEditor.Animations.ChildMotion{motion=run,threshold=2,timeScale=1}};
State("SwordWalk").motion=walk;State("SwordSlash").motion=attack;var strike=State("BatAttack");strike.motion=attack;strike.speed=1;strike.speedParameterActive=false;
foreach(var t in sm.anyStateTransitions.Where(t=>t.destinationState==strike).ToArray())sm.RemoveAnyStateTransition(t);
var enter=sm.AddAnyStateTransition(strike);enter.hasExitTime=false;enter.hasFixedDuration=true;enter.duration=.07f;enter.canTransitionToSelf=false;enter.AddCondition(UnityEditor.Animations.AnimatorConditionMode.If,0,"Attack");
foreach(var t in strike.transitions.ToArray())strike.RemoveTransition(t);var recover=strike.AddTransition(locomotion);recover.hasExitTime=true;recover.exitTime=.96f;recover.hasFixedDuration=true;recover.duration=.08f;
UnityEditor.EditorUtility.SetDirty(tree);UnityEditor.EditorUtility.SetDirty(controller);
var instance=(GameObject)UnityEditor.PrefabUtility.InstantiatePrefab(UnityEditor.AssetDatabase.LoadAssetAtPath<GameObject>(folder+"/SimpleBandit.prefab"));
try{UnityEditor.PrefabUtility.UnpackPrefabInstance(instance,UnityEditor.PrefabUnpackMode.Completely,UnityEditor.InteractionMode.AutomatedAction);
 foreach(var r in instance.GetComponentsInChildren<Renderer>(true).Where(r=>r.name=="Bandit_Bat"||r.name=="Bandit_Club"||r.name=="BanditClub").ToArray())UnityEngine.Object.DestroyImmediate(r.gameObject);
 var socket=instance.GetComponentsInChildren<Transform>(true).Single(t=>t.name=="HandSocket.R");var club=(GameObject)UnityEditor.PrefabUtility.InstantiatePrefab(UnityEditor.AssetDatabase.LoadAssetAtPath<GameObject>(folder+"/Weapons/BanditClub.prefab"));club.transform.SetParent(socket,false);var s=socket.lossyScale;club.transform.localScale=new Vector3(1/s.x,1/s.y,1/s.z);
 var animator=instance.GetComponentInChildren<Animator>();animator.runtimeAnimatorController=controller;animator.applyRootMotion=false;
 UnityEditor.PrefabUtility.SaveAsPrefabAsset(instance,folder+"/SimpleBandit.prefab");
}finally{UnityEngine.Object.DestroyImmediate(instance);}
UnityEditor.AssetDatabase.SaveAssets();foreach(var pair in hashes)if(!pair.Value.SequenceEqual(System.IO.File.ReadAllBytes(pair.Key)))throw new System.Exception("Protected asset changed: "+pair.Key);
var result=new{ready=true,idleSeconds=idle.length,walkSeconds=walk.length,runSeconds=run.length,attackSeconds=attack.length,weaponLength= savedMesh.bounds.size.y,bodyRenderers=1,weaponIsRigid=true,existingBanditsReplaced=false,playerUnchanged=true,attackWindupNormalized=.30f,attackImpactNormalized=.385f};
System.IO.File.WriteAllText("D:/Demo/ArtWork/SimpleBandit/CombatReview/SetupCheck.json",Newtonsoft.Json.JsonConvert.SerializeObject(result,Newtonsoft.Json.Formatting.Indented));return result;

