// Geometry-stage setup. Follow with setup_simple_bandit_combat.cs to restore
// the dedicated rigid club and bandit-owned animation controller after rebuilding.
const string folder="Assets/ChibiSurvivor/Bandit/SimpleBandit";const string hero="Assets/ChibiSurvivor/Player/SimpleHeroStudy/Game";const string modelPath=folder+"/SimpleBandit.fbx";
UnityEditor.AssetDatabase.Refresh();if(!UnityEditor.AssetDatabase.IsValidFolder(folder+"/Materials"))UnityEditor.AssetDatabase.CreateFolder(folder,"Materials");
var importer=(UnityEditor.ModelImporter)UnityEditor.AssetImporter.GetAtPath(modelPath);importer.animationType=UnityEditor.ModelImporterAnimationType.Generic;importer.avatarSetup=UnityEditor.ModelImporterAvatarSetup.CreateFromThisModel;importer.importAnimation=false;importer.importCameras=false;importer.importLights=false;importer.isReadable=true;
var texturePath=folder+"/Textures/SimpleBandit_BaseColor.png";var ti=(UnityEditor.TextureImporter)UnityEditor.AssetImporter.GetAtPath(texturePath);ti.sRGBTexture=true;ti.textureCompression=UnityEditor.TextureImporterCompression.Uncompressed;ti.maxTextureSize=2048;ti.wrapMode=TextureWrapMode.Clamp;ti.SaveAndReimport();
var materialPath=folder+"/Materials/SimpleBandit_Surface.mat";var material=UnityEditor.AssetDatabase.LoadAssetAtPath<Material>(materialPath);if(material==null){material=new Material(Shader.Find("Universal Render Pipeline/Lit"));material.name="SimpleBandit_Surface";material.SetColor("_BaseColor",Color.white);material.SetFloat("_Metallic",0);material.SetFloat("_Smoothness",.1f);material.SetFloat("_SpecularHighlights",0);material.EnableKeyword("_SPECULARHIGHLIGHTS_OFF");UnityEditor.AssetDatabase.CreateAsset(material,materialPath);}material.SetTexture("_BaseMap",UnityEditor.AssetDatabase.LoadAssetAtPath<Texture2D>(texturePath));UnityEditor.EditorUtility.SetDirty(material);
importer.AddRemap(new UnityEditor.AssetImporter.SourceAssetIdentifier(typeof(Material),"SimpleBandit_Surface"),material);
foreach(var name in new[]{"Bandit_BatWood","Bandit_wrap"}){var mat=UnityEditor.AssetDatabase.LoadAssetAtPath<Material>("Assets/ChibiSurvivor/Player/SimpleHeroStudy/Materials/Player_"+name+".mat");if(mat==null)throw new System.Exception("Missing bat material");importer.AddRemap(new UnityEditor.AssetImporter.SourceAssetIdentifier(typeof(Material),name),mat);}importer.SaveAndReimport();
var model=UnityEditor.AssetDatabase.LoadAssetAtPath<GameObject>(modelPath);var controllerPath=folder+"/SimpleBandit.controller";var controller=UnityEditor.AssetDatabase.LoadAssetAtPath<UnityEditor.Animations.AnimatorController>(controllerPath);if(controller==null)controller=UnityEditor.Animations.AnimatorController.CreateAnimatorControllerAtPath(controllerPath);
if(!controller.parameters.Any(p=>p.name=="Speed"))controller.AddParameter("Speed",AnimatorControllerParameterType.Float);
AnimationClip Clip(string name){var clip=UnityEditor.AssetDatabase.LoadAssetAtPath<AnimationClip>(hero+"/"+name+".anim");if(clip==null)throw new System.Exception("Missing "+name);return clip;}
var machine=controller.layers[0].stateMachine;UnityEditor.Animations.AnimatorState State(string name)=>machine.states.Select(s=>s.state).FirstOrDefault(s=>s.name==name)??machine.AddState(name);
var locomotion=State("Locomotion");var tree=locomotion.motion as UnityEditor.Animations.BlendTree;if(tree==null){tree=new UnityEditor.Animations.BlendTree{name="BanditLocomotion",blendType=UnityEditor.Animations.BlendTreeType.Simple1D,blendParameter="Speed",useAutomaticThresholds=false};UnityEditor.AssetDatabase.AddObjectToAsset(tree,controller);}tree.children=new[]{new UnityEditor.Animations.ChildMotion{motion=Clip("Idle"),threshold=0,timeScale=1},new UnityEditor.Animations.ChildMotion{motion=Clip("Walk"),threshold=1,timeScale=1},new UnityEditor.Animations.ChildMotion{motion=Clip("Run"),threshold=2,timeScale=1}};locomotion.motion=tree;machine.defaultState=locomotion;State("SwordWalk").motion=Clip("BatWalk");State("SwordSlash").motion=Clip("BatSwing");
if(!controller.layers.Any(l=>l.name=="SwordHold"))controller.AddLayer("SwordHold");var layers=controller.layers;var holdLayer=layers.Single(l=>l.name=="SwordHold");holdLayer.avatarMask=UnityEditor.AssetDatabase.LoadAssetAtPath<AvatarMask>(hero+"/SwordUpperBody.mask");holdLayer.defaultWeight=1;holdLayer.blendingMode=UnityEditor.Animations.AnimatorLayerBlendingMode.Override;var hold=holdLayer.stateMachine.states.Select(s=>s.state).FirstOrDefault(s=>s.name=="Hold")??holdLayer.stateMachine.AddState("Hold");hold.motion=Clip("BatWalk");hold.speed=0;holdLayer.stateMachine.defaultState=hold;controller.layers=layers;UnityEditor.EditorUtility.SetDirty(tree);UnityEditor.EditorUtility.SetDirty(controller);
var instance=(GameObject)UnityEditor.PrefabUtility.InstantiatePrefab(model);try{instance.name="SimpleBandit";var animator=instance.GetComponentInChildren<Animator>();if(animator==null)animator=instance.AddComponent<Animator>();animator.runtimeAnimatorController=controller;animator.applyRootMotion=false;animator.cullingMode=AnimatorCullingMode.AlwaysAnimate;
foreach(var smr in instance.GetComponentsInChildren<SkinnedMeshRenderer>(true)){smr.updateWhenOffscreen=true;smr.enabled=true;smr.gameObject.SetActive(true);if(smr.sharedMaterials.Any(m=>m==null)||smr.bones.Any(b=>b==null))throw new System.Exception("Missing bandit references "+smr.name);}
UnityEditor.PrefabUtility.SaveAsPrefabAsset(instance,folder+"/SimpleBandit.prefab");}finally{UnityEngine.Object.DestroyImmediate(instance);}UnityEditor.AssetDatabase.SaveAssets();
return new{prefab=folder+"/SimpleBandit.prefab",bodyMaterial=materialPath,sharedMotionClips=true,existingBanditsReplaced=false};
