const string game="Assets/ChibiSurvivor/Player/SimpleHeroStudy/Game";
var prefab=UnityEditor.AssetDatabase.LoadAssetAtPath<GameObject>(game+"/SimpleHero.prefab");var controller=UnityEditor.AssetDatabase.LoadAssetAtPath<RuntimeAnimatorController>(game+"/SimpleHero.controller");
var item=UnityEditor.AssetDatabase.LoadAssetAtPath<ItemData>("Assets/Resources/Items/Weapon/Bat.asset");var w=item.weaponData;if(w==null||!w.useTwoHandBatAnimations||w.useTwoHandSwordAnimations||w.lightCombo.StepCount!=1)throw new System.Exception("Bat routing");
foreach(var atk in new[]{w.lightCombo.GetStep(0),w.heavyAttack,w.heavyFullAttack})if(Mathf.Abs(atk.Duration-1.6f)>.001f||atk.windows.Any(x=>x.startFrame!=17||x.endFrame!=21))throw new System.Exception("Attack timing");
var root=new GameObject("Verify_Player_Bat");root.hideFlags=HideFlags.HideAndDontSave;var visual=root.AddComponent<ChibiPlayerVisual>();var report=new System.Collections.Generic.List<object>();
try{
 if(!visual.Initialize(prefab,controller,null,1)||!visual.HasBatAnimations||!visual.HasSwordAnimations)throw new System.Exception("Initialize");
 var animator=root.GetComponentInChildren<Animator>();animator.Rebind();animator.Update(0);var transforms=root.GetComponentsInChildren<Transform>();var r=transforms.Single(t=>t.name=="HandSocket.R");var l=transforms.Single(t=>t.name=="HandSocket.L");var bat=root.GetComponentsInChildren<Renderer>().Single(x=>x.name=="Hero_Bat");var sword=root.GetComponentsInChildren<Renderer>().Single(x=>x.name=="Hero_SwordProxy");
 if(bat.enabled||sword.enabled)throw new System.Exception("Initial weapon visibility");
 foreach(var speed in new[]{0f,1f,2f}){visual.SetMeleeEquipped(true,true);float grip=0;for(int i=0;i<70;i++){visual.UpdateMotion(Vector2.up,speed,speed==2,true,1,.02f);animator.Update(.02f);if(i>20)grip=Mathf.Max(grip,Vector3.Distance(l.position,r.position-r.up*.15f));}var clip=animator.GetCurrentAnimatorClipInfo(0).OrderByDescending(x=>x.weight).First().clip.name;var expected=speed==0?"Idle":speed==1?"BatWalk":"Run";if(clip!=expected||!bat.enabled||sword.enabled||grip>.012f)throw new System.Exception("Bat locomotion "+clip+" grip "+grip);report.Add(new{clip,grip});}
 visual.PlayMeleeAttack(1.6f,Vector2.up,true);float attackGrip=0;var worstFrame=0;for(int i=0;i<75;i++){visual.UpdateMotion(Vector2.up,0,false,false,1,.02f);animator.Update(.02f);if(i>6){var error=Vector3.Distance(l.position,r.position-r.up*.15f);if(error>attackGrip){attackGrip=error;worstFrame=i;}}}if(attackGrip>.012f||!animator.GetCurrentAnimatorClipInfo(0).Any(x=>x.clip.name=="BatSwing"&&x.weight>.9f))throw new System.Exception("Bat attack "+attackGrip+" frame "+worstFrame);
 visual.CancelAttack();visual.SetSwordEquipped(true);for(int i=0;i<20;i++){visual.UpdateMotion(Vector2.up,1,false,true,1,.02f);animator.Update(.02f);}if(bat.enabled||!sword.enabled)throw new System.Exception("Switch to sword");
 visual.SetMeleeEquipped(false,false);visual.UpdateMotion(Vector2.up,0,false,true,1,.02f);animator.Update(.2f);if(bat.enabled||sword.enabled)throw new System.Exception("Unequip");
 var materials=root.GetComponentsInChildren<SkinnedMeshRenderer>().SelectMany(x=>x.sharedMaterials).Distinct().ToArray();if(materials.Length!=2||materials.Any(m=>m.GetTexture("_BaseMap")==null))throw new System.Exception("Character textures changed");
 var result=new{passed=true,locomotion=report,attackGrip,singleHit=true,attackSeconds=1.6f,weaponSwitch=true,unequip=true,scenePlayTest=false};System.IO.File.WriteAllText("Library/player-bat-verify.json",Newtonsoft.Json.JsonConvert.SerializeObject(result,Newtonsoft.Json.Formatting.Indented));return result;
}finally{typeof(ChibiPlayerVisual).GetField("view",System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.NonPublic).SetValue(visual,null);UnityEngine.Object.DestroyImmediate(root);}
