if(UnityEditor.EditorApplication.isPlaying)throw new System.Exception("Preserve ongoing Play; scene placement needs stopped editor.");
const string stage="D:/Demo/ArtWork/TownFinish62",folder="Assets/Art/Environments/TownFinish62";
var scene=UnityEngine.SceneManagement.SceneManager.GetSceneByName("Safehouse");
if(!scene.isLoaded||scene.isDirty)throw new System.Exception("Safehouse not loaded or has unsaved edits.");
var map=scene.GetRootGameObjects().Single(g=>g.name=="Map");
if(map.transform.Find("Pawnshop_Forecourt62")!=null)throw new System.Exception("Forecourt already exists.");
System.IO.Directory.CreateDirectory(stage+"/BeforeFiles");if(!System.IO.File.Exists(stage+"/BeforeFiles/Safehouse.unity"))System.IO.File.Copy(scene.path,stage+"/BeforeFiles/Safehouse.unity",false);
System.Func<string> gameplay=()=>Newtonsoft.Json.JsonConvert.SerializeObject(new{colliders=map.GetComponentsInChildren<Collider>(true).Select(c=>new{id=UnityEditor.AnimationUtility.CalculateTransformPath(c.transform,map.transform),json=UnityEditor.EditorJsonUtility.ToJson(c),p=c.transform.position.ToString()}),behaviours=map.GetComponentsInChildren<MonoBehaviour>(true).Where(b=>b!=null).Select(b=>new{id=UnityEditor.AnimationUtility.CalculateTransformPath(b.transform,map.transform),json=UnityEditor.EditorJsonUtility.ToJson(b)})});
var baseline=gameplay();
if(!UnityEditor.AssetDatabase.IsValidFolder(folder))UnityEditor.AssetDatabase.CreateFolder("Assets/Art/Environments","TownFinish62");
foreach(var sub in new[]{"Materials","Meshes","Textures","Prefabs"})if(!UnityEditor.AssetDatabase.IsValidFolder(folder+"/"+sub))UnityEditor.AssetDatabase.CreateFolder(folder,sub);
string texturePath=folder+"/Textures/Forecourt_Asphalt.png";System.IO.File.Copy(stage+"/Forecourt_Asphalt.png",texturePath,false);UnityEditor.AssetDatabase.ImportAsset(texturePath);
var ti=(UnityEditor.TextureImporter)UnityEditor.AssetImporter.GetAtPath(texturePath);ti.textureType=UnityEditor.TextureImporterType.Default;ti.sRGBTexture=true;ti.mipmapEnabled=true;ti.maxTextureSize=2048;ti.npotScale=UnityEditor.TextureImporterNPOTScale.None;ti.wrapMode=TextureWrapMode.Repeat;ti.filterMode=FilterMode.Trilinear;ti.anisoLevel=4;ti.textureCompression=UnityEditor.TextureImporterCompression.CompressedHQ;ti.SaveAndReimport();
var town="Assets/Art/Environments/Town02/Materials/";
System.Func<string,Material> tm=n=>UnityEditor.AssetDatabase.LoadAssetAtPath<Material>(town+n+".mat");
var asphalt=new Material(tm("Town_Asphalt")){name="Forecourt_Asphalt"};asphalt.SetTexture("_BaseMap",UnityEditor.AssetDatabase.LoadAssetAtPath<Texture2D>(texturePath));asphalt.SetColor("_BaseColor",new Color(.64f,.64f,.60f,1));asphalt.SetFloat("_BumpScale",.3f);asphalt.SetFloat("_GrimeStrength",.07f);UnityEditor.AssetDatabase.CreateAsset(asphalt,folder+"/Materials/Forecourt_Asphalt.mat");
var slabMats=new Material[3];for(int i=0;i<3;i++){slabMats[i]=new Material(tm("Town_Concrete")){name="Forecourt_Slab_"+i};var c=slabMats[i].GetColor("_BaseColor");float v=.92f+i*.055f;slabMats[i].SetColor("_BaseColor",new Color(c.r*v,c.g*v,c.b*v,1));UnityEditor.AssetDatabase.CreateAsset(slabMats[i],folder+"/Materials/"+slabMats[i].name+".mat");}
var seam=new Material(tm("Town_Dirt")){name="Forecourt_Seam"};seam.SetColor("_BaseColor",new Color(.32f,.31f,.27f,1));seam.SetFloat("_Metallic",0);seam.SetFloat("_Smoothness",0);UnityEditor.AssetDatabase.CreateAsset(seam,folder+"/Materials/Forecourt_Seam.mat");
var root=new GameObject("Pawnshop_Forecourt62");UnityEngine.SceneManagement.SceneManager.MoveGameObjectToScene(root,scene);root.transform.SetParent(map.transform,false);
int hidden=0,slabs=0;foreach(var r in map.GetComponentsInChildren<MeshRenderer>(true)){
 var p=r.bounds.center;if(p.x<25||p.x>43||p.z<34||p.z>38)continue;
 if(r.name=="Weathered_Slab"&&p.z<36){r.enabled=false;hidden++;}
 else if(r.name=="Weathered_Slab"){r.sharedMaterials=Enumerable.Repeat(slabMats[Mathf.RoundToInt(p.x)%3],r.sharedMaterials.Length).ToArray();r.SetPropertyBlock(null);slabs++;}
 if(r.name=="Surface_Crack"){r.enabled=false;hidden++;}
}
// One low irregular repair surface joins the shop walkway to the plaza. Existing floor collision stays in place.
var edge=new System.Collections.Generic.List<Vector3>();for(int i=0;i<=18;i++)edge.Add(new Vector3(25+i,.052f,32.35f+.13f*Mathf.Sin(i*2.1f)+.07f*Mathf.Cos(i*4.2f)));edge.Add(new Vector3(43.15f,.052f,34));edge.Add(new Vector3(43.0f,.052f,36));edge.Add(new Vector3(25,.052f,36));edge.Add(new Vector3(24.9f,.052f,34));
var vertices=new System.Collections.Generic.List<Vector3>{new Vector3(34,.052f,34.1f)};vertices.AddRange(edge);var indices=new System.Collections.Generic.List<int>();for(int i=0;i<edge.Count;i++){indices.Add(0);indices.Add(1+(i+1)%edge.Count);indices.Add(1+i);}
var mesh=new Mesh{name="Forecourt_RepairSurface"};mesh.vertices=vertices.ToArray();mesh.triangles=indices.ToArray();mesh.uv=vertices.Select(p=>new Vector2(p.x/5.5f,p.z/5.5f)).ToArray();mesh.RecalculateNormals();mesh.RecalculateTangents();mesh.RecalculateBounds();UnityEditor.AssetDatabase.CreateAsset(mesh,folder+"/Meshes/Forecourt_RepairSurface.asset");var ground=new GameObject("Repair_Asphalt");ground.transform.SetParent(root.transform,false);ground.AddComponent<MeshFilter>().sharedMesh=mesh;var gr=ground.AddComponent<MeshRenderer>();gr.sharedMaterial=asphalt;gr.shadowCastingMode=UnityEngine.Rendering.ShadowCastingMode.Off;
var palette=(Newtonsoft.Json.Linq.JObject)Newtonsoft.Json.Linq.JObject.Parse(System.IO.File.ReadAllText("Assets/Art/Environments/TownProps02/KitManifest.json"))["palette"];var mats=new System.Collections.Generic.Dictionary<string,Material>();
System.Func<Material,Material> mapMat=original=>{
 if(original==null)throw new System.Exception("Missing prop material");if(original.name.StartsWith("Town_")){var linked=tm(original.name);if(linked!=null)return linked;}if(original.shader.name=="BRB/GameLit")return original;if(mats.ContainsKey(original.name))return mats[original.name];
 var data=palette[original.name];if(data==null)throw new System.Exception("Unknown prop palette: "+original.name);string family=(string)data["family"],texRoot=(string)data["textureFolder"]+"/";
 var m=new Material(tm(family=="Wood"?"Town_Wood":family=="Steel"?"Town_Steel":"Town_Canvas")){name=original.name};var c=data["color"];m.SetColor("_BaseColor",new Color((float)c[0],(float)c[1],(float)c[2],1).gamma);
 m.SetTexture("_BaseMap",UnityEditor.AssetDatabase.LoadAssetAtPath<Texture2D>(texRoot+family+"_Base.png"));m.SetTexture("_BumpMap",UnityEditor.AssetDatabase.LoadAssetAtPath<Texture2D>(texRoot+family+"_Normal.png"));m.SetTexture("_MetallicGlossMap",UnityEditor.AssetDatabase.LoadAssetAtPath<Texture2D>(texRoot+family+"_Mask.png"));m.SetFloat("_BumpScale",(float)data["normalStrength"]);m.SetFloat("_Metallic",(float)data["metallic"]);m.SetFloat("_Smoothness",1);m.SetFloat("_GrimeStrength",.08f);m.SetFloat("_RimStrength",0);m.EnableKeyword("_GAMELIT_PACKED_MASK");m.SetFloat("_UsePackedMask",1);m.EnableKeyword("_ENVIRONMENTREFLECTIONS_OFF");UnityEditor.AssetDatabase.CreateAsset(m,folder+"/Materials/"+m.name+".mat");mats.Add(original.name,m);return m;
};
var placements=new System.Collections.Generic.List<object>();
System.Action<string,Vector3,float> prop=(name,pos,yaw)=>{
 string kit=name=="YardChair02"?"Town02":"TownProps02",asset="Assets/Art/Environments/"+kit+"/Models/"+name+".fbx";var model=UnityEditor.AssetDatabase.LoadAssetAtPath<GameObject>(asset);if(model==null)throw new System.Exception(asset);
 var go=(GameObject)UnityEditor.PrefabUtility.InstantiatePrefab(model,scene);go.transform.SetParent(root.transform,false);go.transform.position=pos;go.transform.rotation=Quaternion.Euler(0,yaw,0);
 foreach(var r in go.GetComponentsInChildren<Renderer>(true))r.sharedMaterials=r.sharedMaterials.Select(mapMat).ToArray();
 foreach(var c in go.GetComponentsInChildren<Collider>(true))UnityEngine.Object.DestroyImmediate(c);
 var renderers=go.GetComponentsInChildren<Renderer>();var bounds=renderers[0].bounds;foreach(var r in renderers)bounds.Encapsulate(r.bounds);placements.Add(new{name,pos=pos.ToString(),size=bounds.size.ToString(),center=bounds.center.ToString()});
};
prop("CardboardStack02",new Vector3(29,.05f,37.15f),-9);prop("YardChair02",new Vector3(30.75f,.05f,37.1f),-18);prop("Toolbox02",new Vector3(38.1f,.05f,37.15f),8);prop("FoldedTarp02",new Vector3(39.2f,.05f,37.2f),-7);prop("Bucket02",new Vector3(37.25f,.05f,37.35f),-12);prop("RopeCoil02",new Vector3(39.65f,.05f,36.7f),15);
// Modest pebbles collect along the repaired lower edge, not in the entrance lane.
var rng=new System.Random(6211);var stone=new Material(tm("Town_Concrete")){name="Forecourt_Aggregate"};stone.SetColor("_BaseColor",new Color(.39f,.37f,.31f,1));UnityEditor.AssetDatabase.CreateAsset(stone,folder+"/Materials/Forecourt_Aggregate.mat");
var vtx=new System.Collections.Generic.List<Vector3>();var tri=new System.Collections.Generic.List<int>();for(int i=0;i<65;i++){float x=25.4f+(float)rng.NextDouble()*17.2f,z=32.13f+(float)rng.NextDouble()*.48f;if(x>32.3f&&x<35.7f)continue;float r=.025f+(float)rng.NextDouble()*.055f;int n=vtx.Count;vtx.Add(new Vector3(x,.055f,z));vtx.Add(new Vector3(x+r,.022f,z+r*.6f));vtx.Add(new Vector3(x+r*.5f,.024f,z-r));vtx.Add(new Vector3(x-r,.026f,z));tri.AddRange(new[]{n,n+1,n+2,n,n+2,n+3,n,n+3,n+1});}
var stones=new Mesh{name="Forecourt_Aggregate"};stones.SetVertices(vtx);stones.SetTriangles(tri,0);stones.uv=vtx.Select(v=>new Vector2(v.x,v.z)).ToArray();stones.RecalculateNormals();stones.RecalculateTangents();UnityEditor.AssetDatabase.CreateAsset(stones,folder+"/Meshes/Forecourt_Aggregate.asset");var gravel=new GameObject("Edge_Aggregate");gravel.transform.SetParent(root.transform,false);gravel.AddComponent<MeshFilter>().sharedMesh=stones;var sr=gravel.AddComponent<MeshRenderer>();sr.sharedMaterial=stone;sr.shadowCastingMode=UnityEngine.Rendering.ShadowCastingMode.Off;
if(gameplay()!=baseline)throw new System.Exception("Existing gameplay/collider state changed.");
int missing=root.GetComponentsInChildren<Transform>(true).Sum(t=>UnityEditor.GameObjectUtility.GetMonoBehavioursWithMissingScriptCount(t.gameObject));if(missing!=0)throw new System.Exception("Missing script.");
UnityEditor.PrefabUtility.SaveAsPrefabAsset(root,folder+"/Prefabs/Pawnshop_Forecourt62.prefab");UnityEditor.SceneManagement.EditorSceneManager.MarkSceneDirty(scene);UnityEditor.SceneManagement.EditorSceneManager.SaveScene(scene);
var result=new{hiddenOldRenderers=hidden,remainingSlabs=slabs,placements,gameplayAndCollidersPreserved=true,missingScripts=missing};System.IO.File.WriteAllText(stage+"/Placement.json",Newtonsoft.Json.JsonConvert.SerializeObject(result,Newtonsoft.Json.Formatting.Indented));return "Forecourt saved; "+hidden+" legacy renderers hidden, 6 props, gameplay and colliders preserved.";
