if(UnityEditor.EditorApplication.isPlaying||UnityEditor.EditorApplication.isCompiling)throw new System.Exception("Ready edit mode required");
const string root="Assets/Art/Environments/Town02",stage="D:/Demo/ArtWork/RenderingReview62";
void Backup(string path){if(string.IsNullOrEmpty(path))return;string to=stage+"/BeforeFiles/"+path;System.IO.Directory.CreateDirectory(System.IO.Path.GetDirectoryName(to));if(!System.IO.File.Exists(to))System.IO.File.Copy(path,to);}
// Import the shader first in a separate MCP call, then apply once the Editor is ready.
// Assigning new texture properties during shader reimport can discard their references.
var shader=Shader.Find("BRB/GameLit");if(shader==null||shader.FindPropertyIndex("_MetallicGlossMap")<0)throw new System.Exception("Packed surface shader not imported");
var weather=UnityEditor.AssetDatabase.LoadAssetAtPath<WeatherData>("Assets/Resources/Data/WeatherData.asset");Backup(UnityEditor.AssetDatabase.GetAssetPath(weather));weather.dayLightColor=new Color(1,.90f,.79f);weather.dayIntensity=.8f;weather.dayAmbientColor=new Color(.34f,.35f,.37f);UnityEditor.EditorUtility.SetDirty(weather);
var profile=UnityEditor.AssetDatabase.LoadAssetAtPath<UnityEngine.Rendering.VolumeProfile>("Assets/Resources/PlayerRigVolume3D.asset");Backup(UnityEditor.AssetDatabase.GetAssetPath(profile));
if(profile.TryGet<UnityEngine.Rendering.Universal.ColorAdjustments>(out var c)){c.contrast.Override(10);c.saturation.Override(-8);c.postExposure.Override(0);UnityEditor.EditorUtility.SetDirty(c);}
if(profile.TryGet<UnityEngine.Rendering.Universal.Bloom>(out var b)){b.intensity.Override(.18f);b.threshold.Override(1.1f);UnityEditor.EditorUtility.SetDirty(b);}
if(profile.TryGet<UnityEngine.Rendering.Universal.FilmGrain>(out var g)){g.intensity.Override(.06f);UnityEditor.EditorUtility.SetDirty(g);}
if(profile.TryGet<UnityEngine.Rendering.Universal.Vignette>(out var vgn)){vgn.intensity.Override(.20f);UnityEditor.EditorUtility.SetDirty(vgn);}UnityEditor.EditorUtility.SetDirty(profile);
void Packed(Material m,Texture map){if(map==null)throw new System.Exception("Missing packed mask: "+m.name);m.SetTexture("_MetallicGlossMap",map);m.SetFloat("_UsePackedMask",1);m.EnableKeyword("_GAMELIT_PACKED_MASK");m.SetFloat("_Metallic",1);m.SetFloat("_Smoothness",1);m.DisableKeyword("_METALLICSPECGLOSSMAP");UnityEditor.EditorUtility.SetDirty(m);UnityEditor.AssetDatabase.SaveAssetIfDirty(m);}
var materialRows=new System.Collections.Generic.List<object>();
foreach(var name in new[]{"Pawnshop","VeteranScavenger","DistrictWarden","WanderingMerchant"}){
 string path="Assets/ChibiSurvivor/NPC/StoryNPC62/Materials/"+name+".mat";Backup(path);var m=UnityEditor.AssetDatabase.LoadAssetAtPath<Material>(path);var mask=UnityEditor.AssetDatabase.LoadAssetAtPath<Texture>("Assets/ChibiSurvivor/NPC/StoryNPC62/Textures/"+name+"/"+name+"_Mask.png");Packed(m,mask);m.SetFloat("_GrimeStrength",.12f);m.SetColor("_GrimeColor",new Color(.65f,.62f,.59f));m.SetFloat("_ShadowDesaturation",.2f);m.SetFloat("_RimStrength",.045f);UnityEditor.EditorUtility.SetDirty(m);materialRows.Add(new{path,mask=mask.name});
}
string folder=root+"/Rendering62";if(!UnityEditor.AssetDatabase.IsValidFolder(folder))UnityEditor.AssetDatabase.CreateFolder(root,"Rendering62");
Material Variant(string name,string source,Vector2 tiling,Color? tint=null){string path=folder+"/"+name+".mat";var m=UnityEditor.AssetDatabase.LoadAssetAtPath<Material>(path);if(m==null){m=new Material(UnityEditor.AssetDatabase.LoadAssetAtPath<Material>(root+"/Materials/"+source+".mat")){name=name};UnityEditor.AssetDatabase.CreateAsset(m,path);}m.shader=shader;m.SetTextureScale("_BaseMap",tiling);if(tint.HasValue)m.SetColor("_BaseColor",tint.Value);m.SetFloat("_BumpScale",.22f);m.SetFloat("_GrimeStrength",.14f);m.SetFloat("_GrimeScale",3);m.SetFloat("_ShadowDesaturation",.25f);m.SetFloat("_RimStrength",0);m.EnableKeyword("_SPECULARHIGHLIGHTS_OFF");m.EnableKeyword("_ENVIRONMENTREFLECTIONS_OFF");var map=m.GetTexture("_MetallicGlossMap");if(map!=null)Packed(m,map);UnityEditor.EditorUtility.SetDirty(m);materialRows.Add(new{path,tiling=tiling.ToString()});return m;}
var renderers=UnityEngine.Object.FindObjectsByType<MeshRenderer>(FindObjectsSortMode.None).Where(r=>r.gameObject.scene.name=="Safehouse").ToArray();
var floor=renderers.Single(r=>r.name=="Floor_In"&&r.transform.parent.name=="Pawnshop");floor.sharedMaterial=Variant("Pawnshop_Floor","Town_Concrete",new Vector2(8,6),new Color(.50f,.48f,.44f));
var counter=renderers.Single(r=>r.name=="Pawn_Counter");counter.sharedMaterial=Variant("Pawnshop_Counter","Town_Wood",new Vector2(4,1),new Color(.52f,.40f,.28f));
var ground=renderers.Single(r=>r.name=="Ground"&&r.bounds.size.x>60);ground.sharedMaterial=Variant("Town_Ground","Town_Dirt",new Vector2(20,14));
foreach(var r in renderers.Where(r=>r.name.StartsWith("Road_")&&r.sharedMaterial!=null&&r.sharedMaterial.name=="Town_Asphalt")){r.sharedMaterial=Variant(r.name,"Town_Asphalt",new Vector2(Mathf.Max(1,r.bounds.size.x/4),Mathf.Max(1,r.bounds.size.z/4)));}
var bulb=UnityEngine.Object.FindObjectsByType<Light>(FindObjectsSortMode.None).Single(l=>l.name=="Bulb"&&l.gameObject.scene.name=="Safehouse");bulb.color=new Color(1,.91f,.80f);bulb.intensity=.8f;bulb.range=9;
var safe=UnityEngine.SceneManagement.SceneManager.GetSceneByName("Safehouse");UnityEditor.SceneManagement.EditorSceneManager.MarkSceneDirty(safe);UnityEditor.SceneManagement.EditorSceneManager.SaveScene(safe);UnityEditor.AssetDatabase.SaveAssets();
var messages=UnityEditor.ShaderUtil.GetShaderMessages(shader).Select(m=>new{m.message,m.file,m.line,severity=m.severity.ToString()}).ToArray();if(messages.Any(m=>m.severity=="Error"))throw new System.Exception("Shader compile errors: "+Newtonsoft.Json.JsonConvert.SerializeObject(messages));
var result=new{materials=materialRows,shaderMessages=messages,weather="day warm key + neutral ambient; night unchanged",profile="contrast10 saturation-8 bloom0.18 grain0.06 vignette0.20"};System.IO.File.WriteAllText(stage+"/Applied.json",Newtonsoft.Json.JsonConvert.SerializeObject(result,Newtonsoft.Json.Formatting.Indented));return Newtonsoft.Json.JsonConvert.SerializeObject(result);
