if(!UnityEditor.EditorApplication.isPlaying)throw new System.Exception("Play required");
var cam=Camera.main;var cd=cam.GetComponent<UnityEngine.Rendering.Universal.UniversalAdditionalCameraData>();var urp=UnityEngine.Rendering.Universal.UniversalRenderPipeline.asset;
if(urp==null||!urp.supportsHDR||!cam.allowHDR||!cd.renderPostProcessing)throw new System.Exception("Camera/URP preflight failed");
var us=new UnityEditor.SerializedObject(urp);var rd=us.FindProperty("m_RendererDataList").GetArrayElementAtIndex(us.FindProperty("m_DefaultRendererIndex").intValue).objectReferenceValue;var rs=new UnityEditor.SerializedObject(rd);var postData=rs.FindProperty("postProcessData");if(postData==null||postData.objectReferenceValue==null)throw new System.Exception("Renderer postprocess data missing");
var volume=UnityEngine.Object.FindObjectsByType<UnityEngine.Rendering.Volume>(FindObjectsSortMode.None).Single(v=>v.name=="PlayerRig Volume");if(!volume.enabled||(cd.volumeLayerMask.value&(1<<volume.gameObject.layer))==0)throw new System.Exception("Volume not visible to camera");
var profile=volume.HasInstantiatedProfile()?volume.profile:volume.sharedProfile;profile.TryGet<UnityEngine.Rendering.Universal.ColorAdjustments>(out var color);profile.TryGet<UnityEngine.Rendering.Universal.Bloom>(out var bloom);profile.TryGet<UnityEngine.Rendering.Universal.FilmGrain>(out var grain);profile.TryGet<UnityEngine.Rendering.Universal.Vignette>(out var vignette);
if(color.contrast.value!=10||color.saturation.value!=-8||Mathf.Abs(bloom.intensity.value-.18f)>.001f)throw new System.Exception("Saved profile did not survive restart");
var shader=Shader.Find("BRB/GameLit");var messages=UnityEditor.ShaderUtil.GetShaderMessages(shader);if(messages.Any(m=>m.severity.ToString()=="Error"))throw new System.Exception("Shader errors");
var materials=new System.Collections.Generic.List<object>();
foreach(var folder in new[]{"Assets/ChibiSurvivor/NPC/StoryNPC62/Materials","Assets/Art/Environments/Town02/Rendering62"})foreach(var guid in UnityEditor.AssetDatabase.FindAssets("t:Material",new[]{folder})){
 var path=UnityEditor.AssetDatabase.GUIDToAssetPath(guid);var m=UnityEditor.AssetDatabase.LoadAssetAtPath<Material>(path);var mask=m.GetTexture("_MetallicGlossMap");var mp=UnityEditor.AssetDatabase.GetAssetPath(mask);var importer=UnityEditor.AssetImporter.GetAtPath(mp) as UnityEditor.TextureImporter;
 if(mask==null||importer==null||importer.sRGBTexture||!m.IsKeywordEnabled("_GAMELIT_PACKED_MASK"))throw new System.Exception("Invalid mask "+path);
 materials.Add(new{path,mask=mp,linear=!importer.sRGBTexture,tiling=m.GetTextureScale("_BaseMap").ToString(),normal=m.GetFloat("_BumpScale")});
}
var legacy=UnityEditor.AssetDatabase.LoadAssetAtPath<Material>("Assets/Art/Environments/Town02/Materials/Town_Dirt.mat");if(legacy.IsKeywordEnabled("_GAMELIT_PACKED_MASK"))throw new System.Exception("Legacy material unexpectedly opted in");
var npc=UnityEngine.Object.FindObjectsByType<NPCController>(FindObjectsSortMode.None).Select(n=>new{id=n.Data.npcId,loop=n.GetComponentInChildren<Animator>().GetCurrentAnimatorStateInfo(0).loop,clip=n.GetComponentInChildren<Animator>().GetCurrentAnimatorClipInfo(0).Single().clip.name,canInteract=n.GetComponent<InteractableObject>().CanInteract}).ToArray();if(npc.Length!=4||npc.Any(n=>!n.loop||!n.canInteract))throw new System.Exception("NPC regression");
var lights=UnityEngine.Object.FindObjectsByType<Light>(FindObjectsSortMode.None).Where(l=>l.gameObject.scene.name=="Safehouse"&&(l.name=="Bulb"||l.name=="PracticalLight")).Select(l=>new{name=l.name,intensity=l.intensity,range=l.range,color=l.color.ToString()}).ToArray();if(lights.Single(l=>l.name=="Bulb").intensity!=4||lights.Where(l=>l.name=="PracticalLight").Any(l=>l.intensity!=6))throw new System.Exception("Light settings did not persist");
var result=new{date="2026-09-11",camera=new{pitch=cam.transform.eulerAngles.x,yaw=cam.transform.eulerAngles.y,hdr=true,postProcessing=true,rendererPostProcessData=postData.objectReferenceValue.name},profile=new{contrast=color.contrast.value,saturation=color.saturation.value,exposure=color.postExposure.value,bloom=bloom.intensity.value,grain=grain.intensity.value,vignette=vignette.intensity.value},materials,npc,lights,legacyMaskOff=true,shaderErrors=0,playing=UnityEditor.EditorApplication.isPlaying};
System.IO.File.WriteAllText("D:/Demo/ArtWork/RenderingReview62/Validation.json",Newtonsoft.Json.JsonConvert.SerializeObject(result,Newtonsoft.Json.Formatting.Indented));return Newtonsoft.Json.JsonConvert.SerializeObject(result);
