var shader=Shader.Find("BRB/GameLit");var messages=UnityEditor.ShaderUtil.GetShaderMessages(shader);if(messages.Any(m=>m.severity.ToString()=="Error"))throw new System.Exception("Shader errors");
var materials=new System.Collections.Generic.List<object>();foreach(var folder in new[]{"Assets/ChibiSurvivor/NPC/StoryNPC62/Materials","Assets/Art/Environments/Town02/Rendering62"})foreach(var guid in UnityEditor.AssetDatabase.FindAssets("t:Material",new[]{folder})){
 var path=UnityEditor.AssetDatabase.GUIDToAssetPath(guid);var m=UnityEditor.AssetDatabase.LoadAssetAtPath<Material>(path);var mask=m.GetTexture("_MetallicGlossMap");var mp=UnityEditor.AssetDatabase.GetAssetPath(mask);var importer=UnityEditor.AssetImporter.GetAtPath(mp) as UnityEditor.TextureImporter;if(mask==null||importer==null||importer.sRGBTexture||!m.IsKeywordEnabled("_GAMELIT_PACKED_MASK"))throw new System.Exception("Invalid mask "+path);materials.Add(new{path,mask=mp,linear=true});}
var profile=UnityEditor.AssetDatabase.LoadAssetAtPath<UnityEngine.Rendering.VolumeProfile>("Assets/Resources/PlayerRigVolume3D.asset");profile.TryGet<UnityEngine.Rendering.Universal.ColorAdjustments>(out var color);profile.TryGet<UnityEngine.Rendering.Universal.Bloom>(out var bloom);profile.TryGet<UnityEngine.Rendering.Universal.FilmGrain>(out var grain);profile.TryGet<UnityEngine.Rendering.Universal.Vignette>(out var vignette);if(color.contrast.value!=10||color.saturation.value!=-8||Mathf.Abs(bloom.intensity.value-.18f)>.001f)throw new System.Exception("Profile persistence failed");
var cam=Camera.main;var cd=cam.GetComponent<UnityEngine.Rendering.Universal.UniversalAdditionalCameraData>();var urp=UnityEngine.Rendering.Universal.UniversalRenderPipeline.asset;var us=new UnityEditor.SerializedObject(urp);var rd=us.FindProperty("m_RendererDataList").GetArrayElementAtIndex(us.FindProperty("m_DefaultRendererIndex").intValue).objectReferenceValue;var rs=new UnityEditor.SerializedObject(rd);var postData=rs.FindProperty("postProcessData");if(!urp.supportsHDR||!cd.renderPostProcessing||postData.objectReferenceValue==null)throw new System.Exception("Post-processing preflight failed");
var npcs=new System.Collections.Generic.List<object>();foreach(var id in new[]{"pawnshop","veteran_scavenger","district_warden","wandering_merchant"}){var prefab=UnityEditor.AssetDatabase.LoadAssetAtPath<GameObject>("Assets/Resources/NPC/"+id+".prefab");var animator=prefab.GetComponentInChildren<Animator>();var clips=animator.runtimeAnimatorController.animationClips;if(clips.Length!=1||!clips[0].isLooping)throw new System.Exception("NPC animation asset regression");npcs.Add(new{id,clip=clips[0].name,seconds=clips[0].length,loop=true});}
var legacy=UnityEditor.AssetDatabase.LoadAssetAtPath<Material>("Assets/Art/Environments/Town02/Materials/Town_Dirt.mat");if(legacy.IsKeywordEnabled("_GAMELIT_PACKED_MASK"))throw new System.Exception("Legacy material unexpectedly changed");
var result=new{date="2026-09-11",shaderErrors=0,materials,npcs,profile=new{contrast=color.contrast.value,saturation=color.saturation.value,bloom=bloom.intensity.value,grain=grain.intensity.value,vignette=vignette.intensity.value},camera=new{pitch=cam.transform.eulerAngles.x,yaw=cam.transform.eulerAngles.y,hdr=true,postProcessing=true,rendererPostProcessData=postData.objectReferenceValue.name},legacyMaskOff=true,scope="Final asset checks and current camera only; user switched to Zone1, preserved ongoing play",nightReview="Intermediate Bulb 8 captured; final Bulb 4 daytime reviewed. Final night recapture deferred after Zone1 switch."};
System.IO.File.WriteAllText("D:/Demo/ArtWork/RenderingReview62/Validation.json",Newtonsoft.Json.JsonConvert.SerializeObject(result,Newtonsoft.Json.Formatting.Indented));
foreach(var label in new[]{"Before","Lighting","Final","Night"})foreach(var id in new[]{"district_warden","pawnshop"})System.IO.File.Copy("Assets/Library/RenderingReview62/"+label+"_"+id+".png","D:/Demo/ArtWork/RenderingReview62/"+label+"_"+id+".png",true);
return Newtonsoft.Json.JsonConvert.SerializeObject(result);
