var shader=Shader.Find("BRB/GameLit");var errors=UnityEditor.ShaderUtil.GetShaderMessages(shader).Where(m=>m.severity.ToString()=="Error").Select(m=>m.message).ToArray();if(errors.Length>0)throw new System.Exception(string.Join("\n",errors));
var mask=new Texture2D(2,2);var mapped=new Material(Shader.Find("Universal Render Pipeline/Lit"));var plain=new Material(mapped.shader);
try{
 mapped.SetTexture("_MetallicGlossMap",mask);mapped.EnableKeyword("_METALLICSPECGLOSSMAP");mapped.SetFloat("_Metallic",0);mapped.SetFloat("_Smoothness",.42f);
 if(!GameLitConverter.Convert(mapped,shader,false)||!mapped.IsKeywordEnabled("_GAMELIT_PACKED_MASK")||mapped.GetTexture("_MetallicGlossMap")!=mask||mapped.GetFloat("_Metallic")!=1||Mathf.Abs(mapped.GetFloat("_Smoothness")-.42f)>.001f)throw new System.Exception("URP mapped material migration failed");
 mapped.SetFloat("_GrimeStrength",.07f);mapped.SetFloat("_RimStrength",.018f);mapped.SetFloat("_ShadowDesaturation",.18f);
 var saved=UnityEditor.EditorJsonUtility.ToJson(mapped);if(GameLitConverter.Convert(mapped,shader,true)||saved!=UnityEditor.EditorJsonUtility.ToJson(mapped))throw new System.Exception("Authored material changed on repeat conversion");
 plain.SetFloat("_Metallic",.25f);plain.SetFloat("_Smoothness",.37f);if(!GameLitConverter.Convert(plain,shader,false)||plain.GetFloat("_Metallic")!=.25f||plain.IsKeywordEnabled("_GAMELIT_PACKED_MASK"))throw new System.Exception("Unmapped scalar preservation failed");
}finally{UnityEngine.Object.DestroyImmediate(mapped);UnityEngine.Object.DestroyImmediate(plain);UnityEngine.Object.DestroyImmediate(mask);}
var paths=UnityEditor.AssetDatabase.FindAssets("t:Material",new[]{"Assets/Art/Environments/Town02","Assets/ChibiSurvivor/NPC/StoryNPC62"}).Select(UnityEditor.AssetDatabase.GUIDToAssetPath).Where(p=>p.EndsWith(".mat"));
int masks=0;foreach(var path in paths){var m=UnityEditor.AssetDatabase.LoadAssetAtPath<Material>(path);if(m.shader!=shader)continue;var tex=m.GetTexture("_MetallicGlossMap");if(tex==null)throw new System.Exception("Missing mask "+path);if(!m.IsKeywordEnabled("_GAMELIT_PACKED_MASK"))throw new System.Exception("Inactive mask "+path);var importer=UnityEditor.AssetImporter.GetAtPath(UnityEditor.AssetDatabase.GetAssetPath(tex)) as UnityEditor.TextureImporter;if(importer.sRGBTexture)throw new System.Exception("sRGB mask "+path);masks++;}
var renderer=UnityEditor.AssetDatabase.LoadAssetAtPath<UnityEngine.Rendering.Universal.UniversalRendererData>("Assets/Settings/ForwardRenderer.asset");var ao=renderer.rendererFeatures.Single(f=>f.GetType().Name=="ScreenSpaceAmbientOcclusion");if(!ao.isActive)throw new System.Exception("AO not active");
var so=new UnityEditor.SerializedObject(ao);var settings=so.FindProperty("m_Settings");
var report=new{shaderErrors=errors,validatedMasks=masks,converterTests=new[]{"URP mapped metal 0 scalar -> intact mask x 1","URP unmapped scalar retained","Repeat conversion preserves authored properties"},aoActive=ao.isActive,aoIntensity=settings.FindPropertyRelative("Intensity").floatValue,aoRadius=settings.FindPropertyRelative("Radius").floatValue,playing=UnityEditor.EditorApplication.isPlaying,compiling=UnityEditor.EditorApplication.isCompiling,temporaryObjects=UnityEngine.Object.FindObjectsByType<Transform>(FindObjectsSortMode.None).Count(t=>t.name=="MaterialReviewCamera"||t.name=="MaterialBoardCamera"||t.name=="CharacterMaterialCamera")};
var text=Newtonsoft.Json.JsonConvert.SerializeObject(report,Newtonsoft.Json.Formatting.Indented);System.IO.File.WriteAllText("D:/Demo/ArtWork/MaterialReview62/Validation.json",text);return text;
