using System;using System.IO;using System.Linq;using System.Collections.Generic;using UnityEngine;using UnityEditor;using UnityEngine.SceneManagement;using Newtonsoft.Json;
public static class WorldComicValidate {
 public static string Run(){
 var scene=SceneManager.GetSceneByName("Safehouse");var map=scene.GetRootGameObjects().Single(g=>g.name=="Map");var root=map.transform.Find("TownLife_Comic62");Physics.SyncTransforms();
 var nc=root.GetComponentsInChildren<Collider>();var old=map.GetComponentsInChildren<Collider>().Where(c=>!c.transform.IsChildOf(root)&&!c.isTrigger&&c.enabled&&c.bounds.max.y>.25f).ToArray();
 var hits=new List<object>();
 var selfHits=new List<object>();for(int i=0;i<nc.Length;i++)for(int j=i+1;j<nc.Length;j++)if(nc[i].bounds.Intersects(nc[j].bounds)&&Physics.ComputePenetration(nc[i],nc[i].transform.position,nc[i].transform.rotation,nc[j],nc[j].transform.position,nc[j].transform.rotation,out var sd,out float depth)&&depth>.06f)selfHits.Add(new{a=nc[i].transform.parent.name,b=nc[j].transform.parent.name,depth});
 foreach(var a in nc)foreach(var b in old)if(a.bounds.Intersects(b.bounds)&&Physics.ComputePenetration(a,a.transform.position,a.transform.rotation,b,b.transform.position,b.transform.rotation,out var dir,out float dist)&&dist>.06f)hits.Add(new{prop=a.transform.parent.name,group=a.transform.parent.parent.name,against=b.name,depth=dist,oldCenter=new[]{b.bounds.center.x,b.bounds.center.y,b.bounds.center.z},oldSize=new[]{b.bounds.size.x,b.bounds.size.y,b.bounds.size.z}});
 var lanes=new[]{new Vector3(12,.6f,36.5f),new Vector3(34,.6f,35),new Vector3(64,.6f,36.5f),new Vector3(22,.6f,27),new Vector3(22,.6f,10),new Vector3(51,.6f,12)}.Select(p=>new{point=new[]{p.x,p.y,p.z},blockedBy=nc.Where(c=>Vector3.Distance(c.ClosestPoint(p),p)<1.2f).Select(c=>c.transform.parent.name).ToArray()}).ToArray();
 var renderers=map.GetComponentsInChildren<Renderer>().Where(r=>r.enabled&&r.gameObject.activeInHierarchy&&r is MeshRenderer||r is SkinnedMeshRenderer).ToArray();
 var result=new{newColliderCount=nc.Length,oversized=nc.Where(c=>c.bounds.size.x>8||c.bounds.size.z>8||c.bounds.size.y>5).Select(c=>c.transform.parent.name).ToArray(),overlaps=hits,selfOverlaps=selfHits,lanes,missingScripts=map.GetComponentsInChildren<Transform>(true).Sum(t=>GameObjectUtility.GetMonoBehavioursWithMissingScriptCount(t.gameObject)),errorShaders=renderers.SelectMany(r=>r.sharedMaterials).Where(m=>m!=null&&m.shader.name.Contains("Error")).Select(m=>m.name).Distinct().ToArray(),untexturedActive=renderers.SelectMany(r=>r.sharedMaterials).Where(m=>m!=null&&m.HasProperty("_BaseMap")&&m.GetTexture("_BaseMap")==null).Select(m=>new{m.name,path=AssetDatabase.GetAssetPath(m)}).Distinct().ToArray()};
 File.WriteAllText(Path.GetFullPath("../ArtWork/WorldComic62/Unity/Validation.json"),JsonConvert.SerializeObject(result,Formatting.Indented));return $"{nc.Length} prop colliders, {hits.Count} overlaps to inspect, {result.oversized.Length} oversized, {result.missingScripts} missing scripts";
 }
}
