using System;using System.IO;using System.Linq;using System.Collections;using System.Collections.Generic;using System.Reflection;using UnityEngine;using UnityEngine.UI;using UnityEditor;using Newtonsoft.Json;
public static class UIProportionReview {
 static string Root=>Path.GetFullPath("../ArtWork/UIProportionReview");
 static string P(Transform t)=>t.parent==null?t.name:P(t.parent)+"/"+t.name;
 public static string Inspect(){
 var cs=UnityEngine.Object.FindObjectsByType<Canvas>(FindObjectsInactive.Include);
 var report=new{screen=new[]{Screen.width,Screen.height},canvases=cs.Select(c=>{var s=c.GetComponent<CanvasScaler>();return new{path=P(c.transform),active=c.gameObject.activeInHierarchy,c.enabled,c.sortingOrder,c.renderMode,c.scaleFactor,rect=c.GetComponent<RectTransform>().rect.ToString(),scaler=s==null?null:new{mode=s.uiScaleMode.ToString(),res=s.referenceResolution.ToString(),match=s.matchWidthOrHeight,screenMatch=s.screenMatchMode.ToString()}};}),prefabs=AssetDatabase.FindAssets("t:Prefab",new[]{"Assets/Resources/UI"}).Select(AssetDatabase.GUIDToAssetPath).SelectMany(p=>AssetDatabase.LoadAssetAtPath<GameObject>(p).GetComponentsInChildren<CanvasScaler>(true).Select(s=>new{path=p,name=s.name,mode=s.uiScaleMode.ToString(),reference=s.referenceResolution.ToString(),s.matchWidthOrHeight})),gameView=typeof(Editor).Assembly.GetType("UnityEditor.GameView").GetProperties(BindingFlags.Public|BindingFlags.NonPublic|BindingFlags.Instance).Where(p=>p.Name.Contains("Size")||p.Name.Contains("size")).Select(p=>new{p.Name,type=p.PropertyType.ToString(),p.CanWrite})};
 File.WriteAllText(Path.Combine(Root,"Inventory.json"),JsonConvert.SerializeObject(report,Formatting.Indented));return "UI inventory saved: "+Screen.width+"x"+Screen.height;}
 public static string Resize(int width,int height){var assembly=typeof(Editor).Assembly;var gvType=assembly.GetType("UnityEditor.GameView");var gv=EditorWindow.GetWindow(gvType);var flags=BindingFlags.Public|BindingFlags.NonPublic|BindingFlags.Instance;
 var sizesType=assembly.GetType("UnityEditor.GameViewSizes");var sizes=typeof(ScriptableSingleton<>).MakeGenericType(sizesType).GetProperty("instance",BindingFlags.Public|BindingFlags.Static).GetValue(null);
 var groupType=assembly.GetType("UnityEditor.GameViewSizeGroupType");var group=sizesType.GetMethod("GetGroup").Invoke(sizes,new[]{Enum.Parse(groupType,"Standalone")});
 var sizeType=assembly.GetType("UnityEditor.GameViewSize");var kind=assembly.GetType("UnityEditor.GameViewSizeType");var name="Codex UI Review "+width+"x"+height;
 int count=(int)group.GetType().GetMethod("GetTotalCount").Invoke(group,null),index=-1;
 for(int i=0;i<count;i++){var size=group.GetType().GetMethod("GetGameViewSize").Invoke(group,new object[]{i});if((string)sizeType.GetProperty("baseText",flags).GetValue(size)==name){index=i;break;}}
 if(index<0){var size=Activator.CreateInstance(sizeType,flags,null,new object[]{Enum.Parse(kind,"FixedResolution"),width,height,name},null);group.GetType().GetMethod("AddCustomSize").Invoke(group,new[]{size});index=count;}
 var prop=gvType.GetProperty("selectedSizeIndex",flags);if(!File.Exists(Path.Combine(Root,"OriginalView.json")))File.WriteAllText(Path.Combine(Root,"OriginalView.json"),JsonConvert.SerializeObject(new{index=(int)prop.GetValue(gv)}));prop.SetValue(gv,index);gv.Repaint();return "Requested "+width+"x"+height;}
 public static string Open(string mode,string tag){UIManager.Instance.CloseAll();PauseMenu.Instance?.Hide();SettingsUI.Hide();
 switch(mode){case "inventory":UIManager.Instance.ShowCharacterPanel();break;case "settings":SettingsUI.Show();break;case "pause":PauseMenu.Show();break;case "map":UnityEngine.Object.FindAnyObjectByType<MapSelectUI>(FindObjectsInactive.Include).Show();break;case "quest":QuestLogUI.Show();break;case "codex":CodexUI.Show();break;case "shop":UIManager.Instance.ShowShop(Resources.LoadAll<ShopData>("Data").First());break;case "bed":UnityEngine.Object.FindObjectsByType<Button>().Single(b=>b.name=="Btn_bed").onClick.Invoke();break;case "hideout":SceneTransitionManager.Instance.TransitionTo("Hideout","default");break;case "town":if(HideoutController.IsActive)SceneTransitionManager.Instance.TransitionTo("Safehouse","from_hideout");break;}
 SceneTransitionManager.Instance.StartCoroutine(Capture(tag));return "Opened "+mode;
 }
 public static string Sweep(string prefix){SceneTransitionManager.Instance.StartCoroutine(SweepRoutine(prefix));return "UI sweep started: "+prefix;}
 public static string FullSweep(){SceneTransitionManager.Instance.StartCoroutine(FullRoutine());return "Three-resolution UI validation started";}
 static IEnumerator FullRoutine(){foreach(var size in new[]{new Vector2Int(1280,1024),new Vector2Int(2560,1080),new Vector2Int(1920,1080)}){Resize(size.x,size.y);yield return new WaitForSecondsRealtime(1);yield return SweepRoutine("Final_"+size.x+"x"+size.y);}Open("town","Final_Town");File.WriteAllText(Path.Combine(Root,"FullSweep-done.txt"),"Complete");}
 public static string Scrolls(){var logs=UnityEngine.Object.FindObjectsByType<ScrollRect>().Select(s=>new{path=P(s.transform),s.enabled,viewport=s.viewport?.rect.ToString(),content=s.content?.rect.ToString(),s.verticalNormalizedPosition,children=s.content?.GetComponentsInChildren<RectTransform>().Select(r=>new{path=P(r),active=r.gameObject.activeInHierarchy,rect=r.rect.ToString(),pos=r.position.ToString(),scale=r.lossyScale.ToString(),text=r.GetComponent<Text>()?.text})});File.WriteAllText(Path.Combine(Root,"Scrolls.json"),JsonConvert.SerializeObject(logs,Formatting.Indented));return "Scrolls saved";}
 static IEnumerator SweepRoutine(string prefix){foreach(var mode in new[]{"town","inventory","map","pause","settings","quest","codex","shop","hideout","bed"}){Open(mode,prefix+"_"+mode);yield return new WaitForSecondsRealtime(3);}File.WriteAllText(Path.Combine(Root,prefix+"-done.txt"),"Completed at "+Screen.width+"x"+Screen.height);}
 static IEnumerator Capture(string tag){yield return new WaitForSecondsRealtime(2);yield return new WaitForEndOfFrame();Canvas.ForceUpdateCanvases();var tex=ScreenCapture.CaptureScreenshotAsTexture();File.WriteAllBytes(Path.Combine(Root,tag+".png"),tex.EncodeToPNG());UnityEngine.Object.Destroy(tex);var rows=new List<object>();
 foreach(var t in UnityEngine.Object.FindObjectsByType<Text>()){
 if(string.IsNullOrWhiteSpace(t.text)||t.color.a<.1f)continue;
 var r=t.rectTransform;var corners=new Vector3[4];r.GetWorldCorners(corners);bool off=corners[0].x< -1||corners[0].y< -1||corners[2].x>Screen.width+1||corners[2].y>Screen.height+1;
 if(t.GetComponentInParent<Mask>()!=null||t.GetComponentInParent<RectMask2D>()!=null)continue;
 if(off||t.preferredHeight>r.rect.height+3||t.preferredWidth>r.rect.width+3)rows.Add(new{path=P(t.transform),t.text,t.fontSize,rect=r.rect.ToString(),preferred=new[]{t.preferredWidth,t.preferredHeight},off});}
 File.WriteAllText(Path.Combine(Root,tag+"-overflow.json"),JsonConvert.SerializeObject(rows,Formatting.Indented));}
}
